/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FuelTypeRequest } from '../model/models';
import { FuelTypeResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateFuelTypeRequestParams {
    fuelTypeRequest: FuelTypeRequest;
}

export interface DeleteFuelTypeByIdRequestParams {
    id: number;
}

export interface FindFuelTypeByNameRequestParams {
    type: string;
}

export interface GetFuelTypeByIdRequestParams {
    id: number;
}

export interface UpdateFuelTypeByIdRequestParams {
    request: FuelTypeRequest;
    id: number;
}


export interface FuelTypeControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createFuelType(requestParameters: CreateFuelTypeRequestParams, extraHttpRequestParams?: any): Observable<FuelTypeResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteFuelTypeById(requestParameters: DeleteFuelTypeByIdRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    findFuelTypeByName(requestParameters: FindFuelTypeByNameRequestParams, extraHttpRequestParams?: any): Observable<Array<FuelTypeResponse>>;

    /**
     * 
     * 
*/
    getAllFuelTypes(extraHttpRequestParams?: any): Observable<Array<FuelTypeResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getFuelTypeById(requestParameters: GetFuelTypeByIdRequestParams, extraHttpRequestParams?: any): Observable<FuelTypeResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateFuelTypeById(requestParameters: UpdateFuelTypeByIdRequestParams, extraHttpRequestParams?: any): Observable<FuelTypeResponse>;

}
